/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentTimelineRouteImport } from './routes/parent.timeline'
import { Route as ParentHomeRouteImport } from './routes/parent.home'
import { Route as ParentGrowthRouteImport } from './routes/parent.growth'
import { Route as ParentCoachingRouteImport } from './routes/parent.coaching'
import { Route as ParentChildRouteImport } from './routes/parent.child'
import { Route as ParentAlertsRouteImport } from './routes/parent.alerts'
import { Route as ParentAlertsAlertIdRouteImport } from './routes/parent.alerts.$alertId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentTimelineRoute = ParentTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ParentRoute,
} as any)
const ParentHomeRoute = ParentHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ParentRoute,
} as any)
const ParentGrowthRoute = ParentGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => ParentRoute,
} as any)
const ParentCoachingRoute = ParentCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildRoute = ParentChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAlertsRoute = ParentAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAlertsAlertIdRoute = ParentAlertsAlertIdRouteImport.update({
  id: '/$alertId',
  path: '/$alertId',
  getParentRoute: () => ParentAlertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/governance': typeof GovernanceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/parent/alerts': typeof ParentAlertsRouteWithChildren
  '/parent/child': typeof ParentChildRoute
  '/parent/coaching': typeof ParentCoachingRoute
  '/parent/growth': typeof ParentGrowthRoute
  '/parent/home': typeof ParentHomeRoute
  '/parent/timeline': typeof ParentTimelineRoute
  '/parent/alerts/$alertId': typeof ParentAlertsAlertIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/governance': typeof GovernanceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/parent/alerts': typeof ParentAlertsRouteWithChildren
  '/parent/child': typeof ParentChildRoute
  '/parent/coaching': typeof ParentCoachingRoute
  '/parent/growth': typeof ParentGrowthRoute
  '/parent/home': typeof ParentHomeRoute
  '/parent/timeline': typeof ParentTimelineRoute
  '/parent/alerts/$alertId': typeof ParentAlertsAlertIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/governance': typeof GovernanceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/parent/alerts': typeof ParentAlertsRouteWithChildren
  '/parent/child': typeof ParentChildRoute
  '/parent/coaching': typeof ParentCoachingRoute
  '/parent/growth': typeof ParentGrowthRoute
  '/parent/home': typeof ParentHomeRoute
  '/parent/timeline': typeof ParentTimelineRoute
  '/parent/alerts/$alertId': typeof ParentAlertsAlertIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/governance'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/parent/alerts'
    | '/parent/child'
    | '/parent/coaching'
    | '/parent/growth'
    | '/parent/home'
    | '/parent/timeline'
    | '/parent/alerts/$alertId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/governance'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/parent/alerts'
    | '/parent/child'
    | '/parent/coaching'
    | '/parent/growth'
    | '/parent/home'
    | '/parent/timeline'
    | '/parent/alerts/$alertId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/governance'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/parent/alerts'
    | '/parent/child'
    | '/parent/coaching'
    | '/parent/growth'
    | '/parent/home'
    | '/parent/timeline'
    | '/parent/alerts/$alertId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GovernanceRoute: typeof GovernanceRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentRoute: typeof ParentRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/timeline': {
      id: '/parent/timeline'
      path: '/timeline'
      fullPath: '/parent/timeline'
      preLoaderRoute: typeof ParentTimelineRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/home': {
      id: '/parent/home'
      path: '/home'
      fullPath: '/parent/home'
      preLoaderRoute: typeof ParentHomeRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/growth': {
      id: '/parent/growth'
      path: '/growth'
      fullPath: '/parent/growth'
      preLoaderRoute: typeof ParentGrowthRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/coaching': {
      id: '/parent/coaching'
      path: '/coaching'
      fullPath: '/parent/coaching'
      preLoaderRoute: typeof ParentCoachingRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/child': {
      id: '/parent/child'
      path: '/child'
      fullPath: '/parent/child'
      preLoaderRoute: typeof ParentChildRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/alerts': {
      id: '/parent/alerts'
      path: '/alerts'
      fullPath: '/parent/alerts'
      preLoaderRoute: typeof ParentAlertsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/alerts/$alertId': {
      id: '/parent/alerts/$alertId'
      path: '/$alertId'
      fullPath: '/parent/alerts/$alertId'
      preLoaderRoute: typeof ParentAlertsAlertIdRouteImport
      parentRoute: typeof ParentAlertsRoute
    }
  }
}

interface ParentAlertsRouteChildren {
  ParentAlertsAlertIdRoute: typeof ParentAlertsAlertIdRoute
}

const ParentAlertsRouteChildren: ParentAlertsRouteChildren = {
  ParentAlertsAlertIdRoute: ParentAlertsAlertIdRoute,
}

const ParentAlertsRouteWithChildren = ParentAlertsRoute._addFileChildren(
  ParentAlertsRouteChildren,
)

interface ParentRouteChildren {
  ParentAlertsRoute: typeof ParentAlertsRouteWithChildren
  ParentChildRoute: typeof ParentChildRoute
  ParentCoachingRoute: typeof ParentCoachingRoute
  ParentGrowthRoute: typeof ParentGrowthRoute
  ParentHomeRoute: typeof ParentHomeRoute
  ParentTimelineRoute: typeof ParentTimelineRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAlertsRoute: ParentAlertsRouteWithChildren,
  ParentChildRoute: ParentChildRoute,
  ParentCoachingRoute: ParentCoachingRoute,
  ParentGrowthRoute: ParentGrowthRoute,
  ParentHomeRoute: ParentHomeRoute,
  ParentTimelineRoute: ParentTimelineRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GovernanceRoute: GovernanceRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ParentRoute: ParentRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
